@extends('admin.layouts.master')
@section('title', $topup->exists ? 'Edit Top-up Plan' : 'Add Top-up Plan')
@section('content')
<div class="container-fluid"><div class="admin-page-header mb-3"><h3><b>{{ $topup->exists ? 'Edit Top-up Plan' : 'Add Top-up Plan' }}</b></h3></div><div class="card"><div class="card-body"><form class="row g-3" method="post" action="{{ $topup->exists ? route('admin.billing.topups.update', $topup) : route('admin.billing.topups.store') }}">@csrf @if($topup->exists) @method('PUT') @endif
<div class="col-md-6"><label class="form-label">Name <span class="text-danger">*</span></label><input class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name', $topup->name) }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Photo Quantity <span class="text-danger">*</span></label><input class="form-control @error('photo_quantity') is-invalid @enderror" type="number" min="1" name="photo_quantity" value="{{ old('photo_quantity', $topup->photo_quantity) }}" required>@error('photo_quantity')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Price <span class="text-danger">*</span></label><input class="form-control @error('price') is-invalid @enderror" type="number" min="0" step="0.01" name="price" value="{{ old('price', $topup->price) }}" required>@error('price')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="state" id="state" value="1" @checked(old('state', $topup->exists ? $topup->state : true))><label class="form-check-label" for="state">Active</label></div></div><div class="col-12"><button class="btn btn-primary">{{ $topup->exists ? 'Update Top-up' : 'Save Top-up' }}</button><a class="btn btn-outline-secondary ms-2" href="{{ route('admin.billing.topups') }}">Cancel</a></div></form></div></div></div>
@endsection
